language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: TYPO3="dev-master as 8.7.0" PHPUNIT=^6.0
    - php: 7.1
      env: TYPO3="dev-master as 8.7.0" PHPUNIT=5.7.5
    - php: 7.1
      env: TYPO3=^8.7 PHPUNIT=^6.0
    - php: 7.1
      env: TYPO3=^8.7 PHPUNIT=5.7.5
    - php: 7.1
      env: TYPO3=^7.6 PHPUNIT=^4.8
    - php: 7.1
      env: TYPO3="7.x-dev" PHPUNIT=^4.8
    - php: 7.0
      env: TYPO3="dev-master as 8.7.0" PHPUNIT=^6.0
    - php: 7.0
      env: TYPO3="dev-master as 8.7.0" PHPUNIT=5.7.5
    - php: 7.0
      env: TYPO3=^8.7 PHPUNIT=^6.0
    - php: 7.0
      env: TYPO3=^8.7 PHPUNIT=5.7.5
    - php: 7.0
      env: TYPO3=^7.6 PHPUNIT=^4.8
    - php: 5.6
      env: TYPO3=^7.6 PHPUNIT=^4.8
    - php: 5.6
      env: TYPO3=^6.2 PHPUNIT=^4.8
    - php: 5.5
      env: TYPO3=^7.6 PHPUNIT=^4.8
    - php: 5.5
      env: TYPO3=^6.2 PHPUNIT=^4.8
    - php: 5.4
      env: TYPO3=^6.2 PHPUNIT=^4.8
    - php: 5.3
      env: TYPO3=^6.2 PHPUNIT=^4.8
  allow_failures:
    - env: TYPO3="dev-master as 8.7.0" PHPUNIT=^6.0
    - env: TYPO3="dev-master as 8.7.0" PHPUNIT=5.7.5

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

before_script:
  - if [ "$TYPO3" == "^6.2" ]; then composer require typo3/cms-composer-installers="1.2.8 as 1.1.4" --no-update; fi
  - composer require typo3/cms="$TYPO3" phpunit/phpunit="$PHPUNIT"
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running unit tests";
    echo;
    echo;
    .Build/bin/phpunit -c res/Configuration/UnitTests.xml .Build/Web/typo3conf/ext/testbase/Tests/Unit/;

  - >
    echo;
    echo "Running functional tests";
    echo;
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find '.Build/Web/typo3conf/ext/testbase/Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit -c res/Configuration/FunctionalTests.xml {}';

  - >
    echo;
    echo "Running php lint";
    echo;
    echo;
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;
